### ISSUE TITLE
Display form notifications in a vertical list

### ISSUE THREAD

**Issue by AllegroVivo** [AllegroVivo/FroggeBotv6#3]
Currently, when listing multiple notification parties for a `Form` (accessed from `/admin forms` > `Modify Form` > `Set Notifications`), if more than one is entered, it's displayed with a comma-separating list. Let's change that to be a vertical list

* Displayed with
* Bullets for each item
* Like this

![image](https://github.com/user-attachments/assets/9129ab84-f61c-4c12-b1d1-6946f3fea008)

**Comment by Mof10** [comment]
Fixed in [PR# 21](https://github.com/AllegroVivo/FroggeBotv6/pull/21)

**Comment by Mof10** [comment]
Fixed in [PR #21](https://github.com/AllegroVivo/FroggeBotv6/pull/21)
